# Generated by Django 4.2.4 on 2023-08-19 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_hosting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagestorage',
            options={'verbose_name_plural': 'Image Storage'},
        ),
        migrations.AlterModelTable(
            name='imagestorage',
            table='image_storage',
        ),
    ]
