# Generated by Django 4.2.4 on 2023-08-21 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('image_hosting', '0003_plan_thumbnail_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagestorage',
            name='valid_till',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
