# Generated by Django 4.2.4 on 2023-08-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_hosting', '0004_imagestorage_valid_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagestorage',
            name='valid_till',
            field=models.DateTimeField(),
        ),
    ]
