# Generated by Django 4.2.4 on 2023-08-21 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image_hosting', '0005_alter_imagestorage_valid_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='image_hosting.plan'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
