# Generated by Django 4.2.4 on 2023-08-21 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_hosting', '0006_alter_subscription_plan_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_hosting.plan'),
        ),
    ]
